/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.alvareztry;

/**
 *
 * @author CL3~PC04
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 240));

        jButton1.setText("M\\/");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 70, 40));

        jButton3.setText("MR");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 70, 40));

        jButton4.setText("M+");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 70, 40));

        jButton5.setText("M-");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 70, 40));

        jButton6.setText("MS");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 70, 40));

        jButton7.setText("MC");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 70, 40));

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton8.setText(".");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, 100, 60));

        jButton31.setBackground(new java.awt.Color(51, 51, 255));
        jButton31.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton31.setText("=");
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 590, 100, 60));

        jButton30.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton30.setText("+");
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 100, 60));

        jButton32.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton32.setText("-");
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 100, 60));

        jButton33.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton33.setText("x");
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 100, 60));

        jButton34.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton34.setText("÷");
        getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 100, 60));

        jButton35.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton35.setText("Delete"); // NOI18N
        jButton35.setToolTipText("");
        getContentPane().add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 100, 60));

        jButton36.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton36.setText("0");
        getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 100, 60));

        jButton37.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton37.setText("√");
        getContentPane().add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 100, 60));

        jButton38.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton38.setText("9");
        getContentPane().add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 100, 60));

        jButton39.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton39.setText("6");
        getContentPane().add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 100, 60));

        jButton40.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton40.setText("3");
        getContentPane().add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 100, 60));

        jButton41.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton41.setText("C");
        getContentPane().add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 100, 60));

        jButton42.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton42.setText("+/-");
        getContentPane().add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 100, 60));

        jButton43.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton43.setText("x²");
        getContentPane().add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 100, 60));

        jButton44.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton44.setText("8");
        getContentPane().add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 100, 60));

        jButton45.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton45.setText("5");
        getContentPane().add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 100, 60));

        jButton46.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton46.setText("2");
        getContentPane().add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 100, 60));

        jButton47.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton47.setText("CE");
        getContentPane().add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 100, 60));

        jButton48.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton48.setText("%");
        getContentPane().add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 100, 60));

        jButton49.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton49.setText("1/x");
        getContentPane().add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 100, 60));

        jButton50.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton50.setText("7");
        getContentPane().add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 100, 60));

        jButton51.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton51.setText("4");
        getContentPane().add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 100, 60));

        jButton52.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton52.setText("1");
        getContentPane().add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 100, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
